### ISSUE TITLE
Error: Unable to load plugin

### ISSUE THREAD

**Issue by Raptoreagle2000** [rdeioris/AnselCapture#2]
Hello

I've tried to use the plugin and it keeps failing at launch. My Unreal is v 4.20.3. 
I have attached the log file and images showing the BP setup. 

I'll appreciate it if you can be of assistance.  

thank you

![ansel bP](https://user-images.githubusercontent.com/48827330/55786534-5943c880-5aac-11e9-8a35-10badac1b687.png)

![ansel error](https://user-images.githubusercontent.com/48827330/55786533-5943c880-5aac-11e9-87bd-812a3c27935a.png)

[Log.txt](https://github.com/rdeioris/AnselCapture/files/3057954/Log.txt)

**Comment by rdeioris** [comment]
Hi,  are you using a binary release or are you building from sources ?

**Comment by Raptoreagle2000** [comment]
I'm using the binary. 
solved the problem but i have another one.. 

The problem was the project was a VR template. When i tried it on the regular 1st person template it worked. 

issue i'm facing now is the the recording is not complete. my scene is set for 300 frames but i only get 177 at the end. There are skips/jumps inbetween the ansel capture. 

thank you for replying!
